AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for our CICD PR'
#basic s3 setup for pr check
Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues: 
      - test
      - staging
      - production
#v3
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-bucket'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GithubActionsTesting
  
  Outputs:
    BucketName:
      Description: 'Name of created s3 bucket'
      Value: !Ref MyS3Bucket